#!/bin/bash
set -e

# Create 
if [ "$1" = "configure" ]; then

    cd "/opt/starwit/sae-detection-sampler"
    python3 -m venv .venv
    source .venv/bin/activate
    pip install -r requirements.txt    

    echo "Create wrapper script"
    mkdir -p /usr/local/bin
    cat > /usr/local/bin/sae-detection-sampler <<EOF
#!/bin/bash

current_dir=$PWD
cd /opt/starwit/sae-detection-sampler
source .venv/bin/activate

python3 main.py "\$@"
cd $current_dir
EOF
    chmod +x /usr/local/bin/sae-detection-sampler

    # link settings file from etc
    cd /opt/starwit/sae-detection-sampler
    ln -sf /etc/starwit/sae-detection-sampler/settings.yaml settings.yaml

    systemctl daemon-reload
    systemctl start sae-detection-sampler.service        
    systemctl enable sae-detection-sampler.service
fi

#DEBHELPER#

exit 0